#!/usr/bin/env node

/**
 * Update drama cover images to use official ShortMax cover art.
 * Points Firestore coverUrl/bannerUrl to the shorttv.live CDN
 * instead of auto-generated video frame captures.
 *
 * Requires a cover-matches.json file generated by the matching script.
 *
 * Usage: GOOGLE_APPLICATION_CREDENTIALS=... node scripts/update-covers.mjs [--dry-run]
 */

import { initializeApp, applicationDefault } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";
import { readFileSync, existsSync } from "fs";

const PROJECT_ID = "shorttv-videos";
const BATCH_SIZE = 400; // Firestore batch limit is 500
const DRY_RUN = process.argv.includes("--dry-run");

const app = initializeApp({
  credential: applicationDefault(),
  projectId: PROJECT_ID,
});

const db = getFirestore(app);

async function main() {
  console.log("=== ShortTV Cover Image Updater ===");
  console.log(`Mode: ${DRY_RUN ? "DRY RUN" : "LIVE"}\n`);

  const matchesFile = "/home/ubuntu/cover-matches.json";
  if (!existsSync(matchesFile)) {
    console.error("No cover-matches.json found. Run the matching script first.");
    process.exit(1);
  }

  const matches = JSON.parse(readFileSync(matchesFile, "utf-8"));
  console.log(`Found ${matches.length} cover matches to process\n`);

  if (DRY_RUN) {
    for (const m of matches.slice(0, 5)) {
      console.log(`  ${m.firestore_slug}: ${m.cover_url.substring(0, 80)}...`);
    }
    console.log(`  ... and ${matches.length - 5} more`);
    return;
  }

  let totalSuccess = 0;
  let totalErrors = 0;

  // Process in Firestore batches
  for (let i = 0; i < matches.length; i += BATCH_SIZE) {
    const chunk = matches.slice(i, i + BATCH_SIZE);
    const batch = db.batch();

    for (const match of chunk) {
      const ref = db.collection("videos").doc(match.firestore_id);
      batch.update(ref, {
        coverUrl: match.cover_url,
        bannerUrl: match.cover_url,
      });
    }

    try {
      await batch.commit();
      totalSuccess += chunk.length;
      console.log(`  Batch ${Math.floor(i / BATCH_SIZE) + 1}: updated ${chunk.length} docs (total: ${totalSuccess})`);
    } catch (err) {
      totalErrors += chunk.length;
      console.log(`  ERROR batch ${Math.floor(i / BATCH_SIZE) + 1}: ${err.message}`);
    }
  }

  console.log(`\n=== Complete ===`);
  console.log(`  Updated: ${totalSuccess}`);
  console.log(`  Errors: ${totalErrors}`);
}

main().catch(console.error);
